[build]
  command = "pip install -r requirements.txt && streamlit run app.py --server.headless true --server.port 8501"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "streamlit run app.py"